version: '2'

services:
    mysqlsrv:
        image: mysql:5.5
        volumes:
          - db_data_mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
          - mysqlsrv
        image: wordpress:latest
        ports:
          - '8010:80'
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysqlsrv:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        volumes:
          - wordpress:/var/www/html
volumes:
    db_data_mysql:
    wordpress:       
